### ISSUE TITLE
Sakura Overlays do not work on boats and signs

### ISSUE THREAD

**Issue by kisachi5** [KiaraFriedPhoenix/KFP-Pack#3]

**Comment by kujxu** [comment]
Idk how to fix this rn without changing textures but we could try to find a solution this evening

**Comment by puyomi2k** [comment]
Since boats and signs are entities and not blocks that won't work. I could try to find out if there's a possible way to apply color schemes to entities but I guess that's not possible.

**Comment by puyomi2k** [comment]
Closed because we moved the Sakura Content to a seperated Addon
